version: '3.8'

services:
  testing-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_BASE_PATH=/api/v1
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  perfect-api:
    build:
      context: .
      dockerfile: Dockerfile.perfect-api
    ports:
      - "8082:8080"
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/test/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  api-network:
    driver: bridge