apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: qualitygate-pipeline
  labels:
    crossplane.io/xrd: xqualitygates.driveby.io
spec:
  compositeTypeRef:
    apiVersion: driveby.io/v1alpha1
    kind: XQualityGate
  mode: Pipeline
  pipeline:
    - step: run-validation
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: driveby-{{ .observed.composite.resource.metadata.name }}
              namespace: driveby
              annotations:
                crossplane.io/external-name: driveby-{{ .observed.composite.resource.metadata.name }}
            spec:
              workflowTemplateRef:
                name: driveby-full-pipeline
              arguments:
                parameters:
                  - name: openapi-url
                    value: "{{ .observed.composite.resource.spec.openapiUrl }}"
                  - name: api-host
                    value: "{{ .observed.composite.resource.spec.apiUrl }}"
                  - name: validation-mode
                    value: "{{ .observed.composite.resource.spec.validationMode }}"
