{{- if .Values.argoEvents.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: driveby-sensor
  namespace: {{ .Values.namespace }}
spec:
  dependencies:
    - name: github-pr
      eventSourceName: driveby-github
      eventName: driveby-webhook
      filters:
        data:
          - path: body.action
            type: string
            value:
              - opened
              - synchronize
  triggers:
    - template:
        name: driveby-pipeline
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: driveby-run-
                namespace: {{ .Values.namespace }}
              spec:
                workflowTemplateRef:
                  name: driveby-full-pipeline
{{- end }}
