# ChangeTransferPolicy — auto-created by the promoter controller from PromotionStrategy
# This example shows the expected output. Do NOT create manually.
apiVersion: promoter.argoproj.io/v1alpha1
kind: ChangeTransferPolicy
metadata:
  name: perfect-api-promotion-environment-dev
  namespace: driveby
spec:
  repositoryReference:
    owner: novelcore
    name: perfect-api
    scmProviderRef:
      name: perfect-api-github
  proposedBranch: environment/dev-next
  activeBranch: environment/dev
  activeCommitStatuses:
    - key: driveby-staging-promotion
  proposedCommitStatuses:
    - key: driveby-staging-promotion
