apiVersion: driveby.io/v1alpha1
kind: XSDLC
metadata:
  name: perfect-api
  namespace: driveby
spec:
  gitopsRepository:
    owner: novelcore
    name: perfect-api-gitops

  apiConfig:
    port: 8000
    openapiEndpoint: /openapi.json

  validationDefaults:
    validationMode: strict

  environments:
    - name: dev

    - name: staging

      gate:
        checks:
          - type: validate-only
            validationConfig:
              validationMode: test-ready
          - type: functional-test
    - name: prod
      autoMerge: false

      gate:
        checks:
          - type: load-test
            loadTestConfig:
              concurrentUsers: 10
              testDuration: "15s"
              maxLatencyP95: "2s"
              minSuccessRate: 0.5
