# DriveBy API Configuration

server:
  host: 0.0.0.0
  port: 8080
  mode: release  # Options: debug, release, test
  timeout: 30s
  shutdown_timeout: 10s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  enabled: true

minio:
  endpoint: localhost:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  use_ssl: false
  bucket_name: driveby
  region: us-east-1
  enabled: true

github:
  api_base_url: https://api.github.com
  default_org: ""  # Default organization for GitHub issues
  default_repo: ""  # Default repository for GitHub issues
  token: ""  # GitHub token for API authentication

logging:
  level: info  # Options: debug, info, warn, error
  format: json  # Options: json, text

testing:
  validation:
    compliance_threshold: 95.0
    fail_on_validation: true
  load_test:
    default_rps: 10
    default_duration: 30s
    default_timeout: 5s
  acceptance:
    default_timeout: 30s

features:
  enable_validation: true
  enable_load_test: true
  enable_acceptance: true
  enable_github: true
  enable_workers: true