{{- if .Values.github.pat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "driveby.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.github.pat | quote }}
{{- end }}
