apiVersion: v1
kind: ServiceAccount
metadata:
  name: driveby
  namespace: driveby
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: driveby
  namespace: driveby
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: driveby
  namespace: driveby
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: driveby
subjects:
  - kind: ServiceAccount
    name: driveby
    namespace: driveby
