apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: driveby-sensor
  namespace: driveby
spec:
  dependencies:
    - name: github-pr
      eventSourceName: driveby-github
      eventName: driveby-webhook
      filters:
        data:
          - path: body.action
            type: string
            value:
              - opened
              - reopened
              - synchronize
  triggers:
    - template:
        name: driveby-staging-promotion
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: driveby-staging-promotion-
                namespace: driveby
              spec:
                workflowTemplateRef:
                  name: driveby-staging-promotion
                arguments:
                  parameters:
                    - name: app-name
                      value: "perfect-api"
                    - name: pr-number
                    - name: head-sha
                    - name: github-owner
                    - name: github-repo
          parameters:
            - src:
                dependencyName: github-pr
                dataKey: body.number
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github-pr
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: github-pr
                dataKey: body.repository.owner.login
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: github-pr
                dataKey: body.repository.name
              dest: spec.arguments.parameters.4.value
