apiVersion: driveby.io/v1alpha1
kind: XSDLC
metadata:
  name: bad-docs-api
  namespace: driveby
spec:
  repository:
    owner: novelcore
    name: bad-docs-api
  gitopsRepository:
    name: bad-docs-api-gitops

  apiConfig:
    port: 8000
    openapiEndpoint: /openapi.json

  validationDefaults:
    validationMode: strict

  environments:
    - name: dev
    - name: staging
      gate:
        checks:
          - type: validate-only
            validationConfig:
              validationMode: strict
