{{- if .Values.crossplane.enabled }}
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
  labels:
    {{- include "driveby.labels" . | nindent 4 }}
spec:
  package: "{{ .Values.crossplane.functions.goTemplating.package }}:{{ .Values.crossplane.functions.goTemplating.version }}"
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
  labels:
    {{- include "driveby.labels" . | nindent 4 }}
spec:
  package: "{{ .Values.crossplane.functions.autoReady.package }}:{{ .Values.crossplane.functions.autoReady.version }}"
{{- end }}
